#! /bin/bash

echo "function run_command()" > run_command.m
echo "train_file='"$1"'" >> run_command.m
echo "dev_file='"$2"'" >> run_command.m
echo "test_file='"$3"'" >> run_command.m
echo "dbn_size="$4 >> run_command.m
echo "save_file='"$5"'" >> run_command.m

echo "[dev_op,test_op] = encode(train_file,dev_file,test_file,dbn_size,save_file)" >> run_command.m

