#! /bin/bash

win_len=$1 # 10 50 or 100

event='filler'
echo $event
# for training 
if [[ ! -f appended_prob_train/$event/training_matrix_$win_len ]]; then
	echo "extracting train features"
	cat appended_prob_train/$event/$win_len/* > prob_file
	perl downsample.pl prob_file prob_file.ds # ds garbage by 20
	cut -d',' -f3- prob_file.ds | sed "s/$event/1/g" | sed 's/filler/0/g;s/laughter/0/g;s/garbage/0/g' > appended_prob_train/$event/training_matrix_$win_len
fi

# for dev set
if [[ ! -f appended_prob_dev/$event/dev_matrix_$win_len ]]; then
	echo "extractin dev features"
	cat appended_prob_dev/$event/$win_len/* > prob_file
	cut -d',' -f3- prob_file | sed "s/$event/1/g" | sed 's/filler/0/g;s/laughter/0/g;s/garbage/0/g' > appended_prob_dev/$event/dev_matrix_$win_len
fi

# for test set
if [[ ! -f appended_prob_test/$event/test_matrix_$win_len ]]; then
	echo "extracting test features"
	cat appended_prob_test/$event/$win_len/* > prob_file
	cut -d',' -f3- prob_file | sed "s/$event/1/g" | sed 's/filler/0/g;s/laughter/0/g;s/garbage/0/g' > appended_prob_test/$event/test_matrix_$win_len
fi

python perform_lstsq.py appended_prob_train/$event/training_matrix_$win_len appended_prob_dev/$event/dev_matrix_$win_len appended_prob_test/$event/test_matrix_$win_len


#####################
#####################

event='laughter'
echo $event
if [[ ! -f appended_prob_train/$event/training_matrix_$win_len ]]; then
        echo "extracting train features"
        cat appended_prob_train/$event/$win_len/* > prob_file
        perl downsample.pl prob_file prob_file.ds # ds garbage by 20
        cut -d',' -f3- prob_file.ds | sed "s/$event/1/g" | sed 's/filler/0/g;s/laughter/0/g;s/garbage/0/g' > appended_prob_train/$event/training_matrix_$win_len
fi

# for dev set
if [[ ! -f appended_prob_dev/$event/dev_matrix_$win_len ]]; then
        echo "extractin dev features"
        cat appended_prob_dev/$event/$win_len/* > prob_file
        cut -d',' -f3- prob_file | sed "s/$event/1/g" | sed 's/filler/0/g;s/laughter/0/g;s/garbage/0/g' > appended_prob_dev/$event/dev_matrix_$win_len
fi

# for test set
if [[ ! -f appended_prob_test/$event/test_matrix_$win_len ]]; then
        echo "extracting test features"
        cat appended_prob_test/$event/$win_len/* > prob_file
        cut -d',' -f3- prob_file | sed "s/$event/1/g" | sed 's/filler/0/g;s/laughter/0/g;s/garbage/0/g' > appended_prob_test/$event/test_matrix_$win_len
fi

python perform_lstsq.py appended_prob_train/$event/training_matrix_$win_len appended_prob_dev/$event/dev_matrix_$win_len appended_prob_test/$event/test_matrix_$win_len 
 
